PR: Before ACES 2.0...
AcademySoftwareFoundation/OpenColorIO-Config-ACES pull request #129
Opened 2024-07-31 06:07 UTC by KelSolaar

This PR implements some improvements and fixes we want to roll on for ACES 1.x support as stated during OSD 2024.

2024-08-02 20:41 UTC, KelSolaar commented
I think that this should address #123, #124 and #127. The configs are here: https://github.com/AcademySoftwareFoundation/OpenColorIO-Config-ACES/actions/runs/10212744897

2024-08-02 20:59 UTC, KelSolaar commented
![image](https://github.com/user-attachments/assets/983694d1-cefd-44d3-9cf5-557a9cc42204)

There are still unsolved discussions about the `Raw` <-> `None` alias and the `sRGB Encoded P3-D65 - Scene-referred` <-> `Display P3` space name.

2024-08-08 05:05 UTC, doug-walker requested changes
Lots of great enhancements here!   A few comments:

1. I notice the contents of cg-config-v2.1.0_aces-v1.3_ocio-v2.3.ocio has changed. The old deliverables should either be dropped from the new generator, or reverted to their original contents.
2. I like the idea of moving the Un-tone-mapped view transform to be first (to work around a bug in earlier versions of the library). But I think the ACES view transform should remain the first one in the displays and active_views, since that will be the default.
3. The description for some of the color spaces has flipped and is now incorrect. For example "Linear P3-D65" now says "Convert linear P3 primaries, D65 white point to ACES2065-1", but it is a from_ref transform so it's the opposite.
4. The color spaces version should be incremented from 2.1.0. Probably 2.2.0?

I haven't finished reviewing yet, but wanted to get you at least some initial thoughts.

2024-08-08 05:18 UTC, doug-walker commented
And a couple more notes:

5. It looks like the Adobe RGB spaces made it into the Studio config but not the CG one. I think for MaterialX compatibility it would be nice to have the CG config have that too.
6. We should probably rename "CIE-XYZ-D65" to "CIE-XYZ-D65 - Display-referred" and put it back into the inactive_colorspaces list.
7. The Color Interop Forum aliases are not right yet. For example lin_rec709_scene is missing and g22_adobergb_scene is adobergb_scene.

More to come probably ...  ;-)

2024-08-08 07:06 UTC, KelSolaar commented on opencolorio_config_aces/clf/transforms/ocio/utility/OCIO.Utility.AP0_to_CIE-XYZ-D65-Scene-referred.clf
> + 0.00107795096161498 -0.00340726320478726     1.00232931224317
Ah, you are right, chromatic adaptation is enabled by default in the `RGB_to_RGB` function, so it will adapt the whitepoint.

2024-08-08 07:07 UTC, KelSolaar commented
1. Is this only because I did not bump the version number yet?
2. Agreed, I was not sure exactly about what you meant in your comment so I moved the view first and mentioned that we should clarify this during the TSC meeting.
3. Interesting, I haven't changed any code pertaining to that, looking at it now they have been wrong for a while:

![image](https://github.com/user-attachments/assets/c0af0785-3bf2-4a9c-bf87-1aa62827b5c3)

4. Yes.
5. Toggle on the spreadsheet.
6. Easy!
7. Ah, I looked at your comment in #127 and assumed it was exhaustive! I will cross-check against the doco table.

2024-08-09 04:24 UTC, doug-walker commented
Replying to each of the previous points:
1. Yes, please bump the color spaces version to 2.2.0 to avoid confusion with the previously released configs.
2. Sounds like we're on the same page about what to change. Let's proceed with that without waiting for the TSC, though we should put it on the list to validate.
3. The descriptions were not wrong in what we released last year, they flipped sometime after that.
4. Good!
5. Thanks!
6. Thanks! One very minor point about the name details. In the ASWF CIF document we have "CIE XYZ-D65 - Scene-referred".  Note that it has a space between CIE and XYZ rather than a dash. My thinking is that "XYZ-D65" is basically the primaries & white point and "CIE" is the "vendor", so a space is better. But I realize we used "CIE-XYZ-D65" in the earlier config. We need to talk about the addition of this space at the CIF meeting on Monday anyway, so I will see if the group has a strong preference.
7. To be specific, here's what is missing:
Missing ASWF CIF compact name: lin_ap1_scene
Missing ASWF CIF compact name: lin_ap0_scene
Missing ASWF CIF compact name: lin_rec709_scene
Missing ASWF CIF compact name: lin_displayp3_scene
Missing ASWF CIF compact name: lin_rec2020_scene
Missing ASWF CIF compact name: lin_adobergb_scene
Missing ASWF CIF compact name: lin_ciexyzd65_scene
Missing ASWF CIF compact name: srgb_rec709_scene
Missing ASWF CIF compact name: srgb_ap1_scene
Missing ASWF CIF compact name: srgb_displayp3_scene
Missing ASWF CIF compact name: g22_adobergb_scene

2024-08-09 05:09 UTC, doug-walker commented
New points:

8. The missing encodings don't seem to have been added.  Specifically, the following are needed:
Missing encoding: CIE-XYZ-D65  -->  'display-linear'
Missing encoding: CIE-XYZ-D65 - Scene-referred  -->  'scene-linear'
Missing encoding: sRGB - Scene-referred  -->  'sdr-video'
Missing encoding: Raw  -->  'data'

9. The display-referred CIE-XYZ-D65 should remain in the inactive list.

2024-08-09 06:33 UTC, KelSolaar commented
Thanks this is super helpful!

2024-08-09 06:42 UTC, KelSolaar commented
3. is looking like a regression introduced in #117.

2024-08-09 09:04 UTC, KelSolaar commented
Regarding the *Un-tonemapped* view, it seems like if we insert it first programmatically in the `shared_views`, it will end up first in the displays.

```yaml
shared_views:
  - !<View> {name: Un-tone-mapped, view_transform: Un-tone-mapped, display_colorspace: <USE_DISPLAY_NAME>}
  - !<View> {name: ACES 1.0 - SDR Video, view_transform: ACES 1.0 - SDR Video, display_colorspace: <USE_DISPLAY_NAME>}
  - !<View> {name: ACES 1.0 - SDR Video (D60 sim on D65), view_transform: ACES 1.0 - SDR Video (D60 sim on D65), display_colorspace: <USE_DISPLAY_NAME>}
  - !<View> {name: ACES 1.1 - SDR Video (P3 lim), view_transform: ACES 1.1 - SDR Video (P3 lim), display_colorspace: <USE_DISPLAY_NAME>}
  - !<View> {name: ACES 1.1 - SDR Video (Rec.709 lim), view_transform: ACES 1.1 - SDR Video (Rec.709 lim), display_colorspace: <USE_DISPLAY_NAME>}
  - !<View> {name: ACES 1.1 - HDR Video (1000 nits & Rec.2020 lim), view_transform: ACES 1.1 - HDR Video (1000 nits & Rec.2020 lim), display_colorspace: <USE_DISPLAY_NAME>}
  - !<View> {name: ACES 1.1 - HDR Video (2000 nits & Rec.2020 lim), view_transform: ACES 1.1 - HDR Video (2000 nits & Rec.2020 lim), display_colorspace: <USE_DISPLAY_NAME>}
  - !<View> {name: ACES 1.1 - HDR Video (4000 nits & Rec.2020 lim), view_transform: ACES 1.1 - HDR Video (4000 nits & Rec.2020 lim), display_colorspace: <USE_DISPLAY_NAME>}
  - !<View> {name: ACES 1.1 - HDR Video (1000 nits & P3 lim), view_transform: ACES 1.1 - HDR Video (1000 nits & P3 lim), display_colorspace: <USE_DISPLAY_NAME>}
  - !<View> {name: ACES 1.1 - HDR Video (2000 nits & P3 lim), view_transform: ACES 1.1 - HDR Video (2000 nits & P3 lim), display_colorspace: <USE_DISPLAY_NAME>}
  - !<View> {name: ACES 1.1 - HDR Video (4000 nits & P3 lim), view_transform: ACES 1.1 - HDR Video (4000 nits & P3 lim), display_colorspace: <USE_DISPLAY_NAME>}
  - !<View> {name: ACES 1.0 - SDR Cinema, view_transform: ACES 1.0 - SDR Cinema, display_colorspace: <USE_DISPLAY_NAME>}
  - !<View> {name: ACES 1.1 - SDR Cinema (Rec.709 lim), view_transform: ACES 1.1 - SDR Cinema (Rec.709 lim), display_colorspace: <USE_DISPLAY_NAME>}
  - !<View> {name: ACES 1.0 - SDR Cinema (D60 sim on DCI), view_transform: ACES 1.0 - SDR Cinema (D60 sim on DCI), display_colorspace: <USE_DISPLAY_NAME>}
  - !<View> {name: ACES 1.1 - SDR Cinema (D60 sim on D65), view_transform: ACES 1.1 - SDR Cinema (D60 sim on D65), display_colorspace: <USE_DISPLAY_NAME>}
  - !<View> {name: ACES 1.1 - SDR Cinema (D65 sim on DCI), view_transform: ACES 1.1 - SDR Cinema (D65 sim on DCI), display_colorspace: <USE_DISPLAY_NAME>}
  - !<View> {name: ACES 1.1 - HDR Cinema (108 nits & P3 lim), view_transform: ACES 1.1 - HDR Cinema (108 nits & P3 lim), display_colorspace: <USE_DISPLAY_NAME>}

displays:
  P3-DCI - Display:
    - !<View> {name: Raw, colorspace: Raw}
    - !<Views> [Un-tone-mapped, ACES 1.0 - SDR Cinema (D60 sim on DCI), ACES 1.1 - SDR Cinema (D65 sim on DCI)]
  P3-D65 - Display:
    - !<View> {name: Raw, colorspace: Raw}
    - !<Views> [Un-tone-mapped, ACES 1.0 - SDR Cinema, ACES 1.1 - SDR Cinema (Rec.709 lim), ACES 1.1 - SDR Cinema (D60 sim on D65)]
  P3-D60 - Display:
    - !<View> {name: Raw, colorspace: Raw}
    - !<Views> [Un-tone-mapped, ACES 1.0 - SDR Cinema]
  ST2084-P3-D65 - Display:
    - !<View> {name: Raw, colorspace: Raw}
    - !<Views> [Un-tone-mapped, ACES 1.1 - HDR Video (1000 nits & P3 lim), ACES 1.1 - HDR Video (2000 nits & P3 lim), ACES 1.1 - HDR Video (4000 nits & P3 lim), ACES 1.1 - HDR Cinema (108 nits & P3 lim)]
  Rec.2100-PQ - Display:
    - !<View> {name: Raw, colorspace: Raw}
    - !<Views> [Un-tone-mapped, ACES 1.1 - HDR Video (1000 nits & Rec.2020 lim), ACES 1.1 - HDR Video (2000 nits & Rec.2020 lim), ACES 1.1 - HDR Video (4000 nits & Rec.2020 lim)]
  Rec.2100-HLG - Display:
    - !<View> {name: Raw, colorspace: Raw}
    - !<Views> [Un-tone-mapped, ACES 1.1 - HDR Video (1000 nits & Rec.2020 lim)]
  Rec.1886 Rec.2020 - Display:
    - !<View> {name: Raw, colorspace: Raw}
    - !<Views> [Un-tone-mapped, ACES 1.0 - SDR Video, ACES 1.1 - SDR Video (P3 lim), ACES 1.1 - SDR Video (Rec.709 lim)]
  Rec.1886 Rec.709 - Display:
    - !<View> {name: Raw, colorspace: Raw}
    - !<Views> [Un-tone-mapped, ACES 1.0 - SDR Video, ACES 1.0 - SDR Video (D60 sim on D65)]
  Display P3 - Display:
    - !<View> {name: Raw, colorspace: Raw}
    - !<Views> [Un-tone-mapped, ACES 1.0 - SDR Video, ACES 1.0 - SDR Video (D60 sim on D65)]
  sRGB - Display:
    - !<View> {name: Raw, colorspace: Raw}
    - !<Views> [Un-tone-mapped, ACES 1.0 - SDR Video, ACES 1.0 - SDR Video (D60 sim on D65)]
```

2024-08-09 22:39 UTC, doug-walker commented
Regarding point 2 (Un-tone-mapped ordering), ideally it would remain where it originally was (i.e., last) for the shared_views and Views and the only part that would move would be the ViewTransform. However, if that become complicated in the code, a workaround could be to use the active_views. The active_views should reorder the views in menus, so you could leave Un-tone-mapped first everywhere and just move it to the end of active_views.

2024-08-09 23:23 UTC, KelSolaar commented
What I'm trying to say is that from the code I cannot seem to have separate control over the position for Shared Views and Displays, put another way the Shared View position controls the Display position.

Those are the are the insertion orders in the code:

```
[ View Transforms ]
ACES 1.0 - SDR Video
ACES 1.0 - SDR Video (D60 sim on D65)
ACES 1.1 - SDR Video (P3 lim)
ACES 1.1 - SDR Video (Rec.709 lim)
ACES 1.1 - HDR Video (1000 nits & Rec.2020 lim)
ACES 1.1 - HDR Video (2000 nits & Rec.2020 lim)
ACES 1.1 - HDR Video (4000 nits & Rec.2020 lim)
ACES 1.1 - HDR Video (1000 nits & P3 lim)
ACES 1.1 - HDR Video (2000 nits & P3 lim)
ACES 1.1 - HDR Video (4000 nits & P3 lim)
ACES 1.0 - SDR Cinema
ACES 1.1 - SDR Cinema (Rec.709 lim)
ACES 1.0 - SDR Cinema (D60 sim on DCI)
ACES 1.1 - SDR Cinema (D60 sim on D65)
ACES 1.1 - SDR Cinema (D65 sim on DCI)
ACES 1.1 - HDR Cinema (108 nits & P3 lim)
Un-tone-mapped

[ Shared Views ]
['Un-tone-mapped', 'P3-DCI - Display']
['Un-tone-mapped', 'P3-D65 - Display']
['Un-tone-mapped', 'P3-D60 - Display']
['Un-tone-mapped', 'ST2084-P3-D65 - Display']
['Un-tone-mapped', 'Rec.2100-PQ - Display']
['Un-tone-mapped', 'Rec.2100-HLG - Display']
['Un-tone-mapped', 'Rec.1886 Rec.2020 - Display']
['Un-tone-mapped', 'Rec.1886 Rec.709 - Display']
['Un-tone-mapped', 'sRGB - Display']
['ACES 1.0 - SDR Video', 'sRGB - Display']
['ACES 1.0 - SDR Video', 'Rec.1886 Rec.709 - Display']
['ACES 1.0 - SDR Video', 'Rec.1886 Rec.2020 - Display']
['ACES 1.0 - SDR Video (D60 sim on D65)', 'sRGB - Display']
['ACES 1.0 - SDR Video (D60 sim on D65)', 'Rec.1886 Rec.709 - Display']
['ACES 1.1 - SDR Video (P3 lim)', 'Rec.1886 Rec.2020 - Display']
['ACES 1.1 - SDR Video (Rec.709 lim)', 'Rec.1886 Rec.2020 - Display']
['ACES 1.1 - HDR Video (1000 nits & Rec.2020 lim)', 'Rec.2100-HLG - Display']
['ACES 1.1 - HDR Video (1000 nits & Rec.2020 lim)', 'Rec.2100-PQ - Display']
['ACES 1.1 - HDR Video (2000 nits & Rec.2020 lim)', 'Rec.2100-PQ - Display']
['ACES 1.1 - HDR Video (4000 nits & Rec.2020 lim)', 'Rec.2100-PQ - Display']
['ACES 1.1 - HDR Video (1000 nits & P3 lim)', 'ST2084-P3-D65 - Display']
['ACES 1.1 - HDR Video (2000 nits & P3 lim)', 'ST2084-P3-D65 - Display']
['ACES 1.1 - HDR Video (4000 nits & P3 lim)', 'ST2084-P3-D65 - Display']
['ACES 1.0 - SDR Cinema', 'P3-D60 - Display']
['ACES 1.0 - SDR Cinema', 'P3-D65 - Display']
['ACES 1.1 - SDR Cinema (Rec.709 lim)', 'P3-D65 - Display']
['ACES 1.0 - SDR Cinema (D60 sim on DCI)', 'P3-DCI - Display']
['ACES 1.1 - SDR Cinema (D60 sim on D65)', 'P3-D65 - Display']
['ACES 1.1 - SDR Cinema (D65 sim on DCI)', 'P3-DCI - Display']
['ACES 1.1 - HDR Cinema (108 nits & P3 lim)', 'ST2084-P3-D65 - Display']
```

And we get that:

```yaml
shared_views:
  - !<View> {name: Un-tone-mapped, view_transform: Un-tone-mapped, display_colorspace: <USE_DISPLAY_NAME>}
  - !<View> {name: ACES 1.0 - SDR Video, view_transform: ACES 1.0 - SDR Video, display_colorspace: <USE_DISPLAY_NAME>}
  - !<View> {name: ACES 1.0 - SDR Video (D60 sim on D65), view_transform: ACES 1.0 - SDR Video (D60 sim on D65), display_colorspace: <USE_DISPLAY_NAME>}
  - !<View> {name: ACES 1.1 - SDR Video (P3 lim), view_transform: ACES 1.1 - SDR Video (P3 lim), display_colorspace: <USE_DISPLAY_NAME>}
  - !<View> {name: ACES 1.1 - SDR Video (Rec.709 lim), view_transform: ACES 1.1 - SDR Video (Rec.709 lim), display_colorspace: <USE_DISPLAY_NAME>}
  - !<View> {name: ACES 1.1 - HDR Video (1000 nits & Rec.2020 lim), view_transform: ACES 1.1 - HDR Video (1000 nits & Rec.2020 lim), display_colorspace: <USE_DISPLAY_NAME>}
  - !<View> {name: ACES 1.1 - HDR Video (2000 nits & Rec.2020 lim), view_transform: ACES 1.1 - HDR Video (2000 nits & Rec.2020 lim), display_colorspace: <USE_DISPLAY_NAME>}
  - !<View> {name: ACES 1.1 - HDR Video (4000 nits & Rec.2020 lim), view_transform: ACES 1.1 - HDR Video (4000 nits & Rec.2020 lim), display_colorspace: <USE_DISPLAY_NAME>}
  - !<View> {name: ACES 1.1 - HDR Video (1000 nits & P3 lim), view_transform: ACES 1.1 - HDR Video (1000 nits & P3 lim), display_colorspace: <USE_DISPLAY_NAME>}
  - !<View> {name: ACES 1.1 - HDR Video (2000 nits & P3 lim), view_transform: ACES 1.1 - HDR Video (2000 nits & P3 lim), display_colorspace: <USE_DISPLAY_NAME>}
  - !<View> {name: ACES 1.1 - HDR Video (4000 nits & P3 lim), view_transform: ACES 1.1 - HDR Video (4000 nits & P3 lim), display_colorspace: <USE_DISPLAY_NAME>}
  - !<View> {name: ACES 1.0 - SDR Cinema, view_transform: ACES 1.0 - SDR Cinema, display_colorspace: <USE_DISPLAY_NAME>}
  - !<View> {name: ACES 1.1 - SDR Cinema (Rec.709 lim), view_transform: ACES 1.1 - SDR Cinema (Rec.709 lim), display_colorspace: <USE_DISPLAY_NAME>}
  - !<View> {name: ACES 1.0 - SDR Cinema (D60 sim on DCI), view_transform: ACES 1.0 - SDR Cinema (D60 sim on DCI), display_colorspace: <USE_DISPLAY_NAME>}
  - !<View> {name: ACES 1.1 - SDR Cinema (D60 sim on D65), view_transform: ACES 1.1 - SDR Cinema (D60 sim on D65), display_colorspace: <USE_DISPLAY_NAME>}
  - !<View> {name: ACES 1.1 - SDR Cinema (D65 sim on DCI), view_transform: ACES 1.1 - SDR Cinema (D65 sim on DCI), display_colorspace: <USE_DISPLAY_NAME>}
  - !<View> {name: ACES 1.1 - HDR Cinema (108 nits & P3 lim), view_transform: ACES 1.1 - HDR Cinema (108 nits & P3 lim), display_colorspace: <USE_DISPLAY_NAME>}

displays:
  P3-DCI - Display:
    - !<View> {name: Raw, colorspace: Raw}
    - !<Views> [Un-tone-mapped, ACES 1.0 - SDR Cinema (D60 sim on DCI), ACES 1.1 - SDR Cinema (D65 sim on DCI)]
  P3-D65 - Display:
    - !<View> {name: Raw, colorspace: Raw}
    - !<Views> [Un-tone-mapped, ACES 1.0 - SDR Cinema, ACES 1.1 - SDR Cinema (Rec.709 lim), ACES 1.1 - SDR Cinema (D60 sim on D65)]
  P3-D60 - Display:
    - !<View> {name: Raw, colorspace: Raw}
    - !<Views> [Un-tone-mapped, ACES 1.0 - SDR Cinema]
  ST2084-P3-D65 - Display:
    - !<View> {name: Raw, colorspace: Raw}
    - !<Views> [Un-tone-mapped, ACES 1.1 - HDR Video (1000 nits & P3 lim), ACES 1.1 - HDR Video (2000 nits & P3 lim), ACES 1.1 - HDR Video (4000 nits & P3 lim), ACES 1.1 - HDR Cinema (108 nits & P3 lim)]
  Rec.2100-PQ - Display:
    - !<View> {name: Raw, colorspace: Raw}
    - !<Views> [Un-tone-mapped, ACES 1.1 - HDR Video (1000 nits & Rec.2020 lim), ACES 1.1 - HDR Video (2000 nits & Rec.2020 lim), ACES 1.1 - HDR Video (4000 nits & Rec.2020 lim)]
  Rec.2100-HLG - Display:
    - !<View> {name: Raw, colorspace: Raw}
    - !<Views> [Un-tone-mapped, ACES 1.1 - HDR Video (1000 nits & Rec.2020 lim)]
  Rec.1886 Rec.2020 - Display:
    - !<View> {name: Raw, colorspace: Raw}
    - !<Views> [Un-tone-mapped, ACES 1.0 - SDR Video, ACES 1.1 - SDR Video (P3 lim), ACES 1.1 - SDR Video (Rec.709 lim)]
  Rec.1886 Rec.709 - Display:
    - !<View> {name: Raw, colorspace: Raw}
    - !<Views> [Un-tone-mapped, ACES 1.0 - SDR Video, ACES 1.0 - SDR Video (D60 sim on D65)]
  Display P3 - Display:
    - !<View> {name: Raw, colorspace: Raw}
    - !<Views> [Un-tone-mapped, ACES 1.0 - SDR Video, ACES 1.0 - SDR Video (D60 sim on D65)]
  sRGB - Display:
    - !<View> {name: Raw, colorspace: Raw}
    - !<Views> [Un-tone-mapped, ACES 1.0 - SDR Video, ACES 1.0 - SDR Video (D60 sim on D65)]
```

Moving it at the end of the `active_views` is trivial.

2024-08-09 23:43 UTC, doug-walker commented
Yes, I understood that. But we don't need separate control for shared_views and views in displays. Un-tone-mapped should be last for both. So in other words, no change from previous configs.  The only thing I was asking to have changed was the order of the view_transforms. Ideally that would be added first rather than last. It should have no correlation to the shared_views or displays.

2024-08-12 02:00 UTC, KelSolaar commented
New artifacts are here: https://github.com/AcademySoftwareFoundation/OpenColorIO-Config-ACES/actions/runs/10338433484

We should be very close!

2024-08-12 02:22 UTC, KelSolaar commented
Noted that the description of `ST-2084 - Curve` is incorrect:

> Convert generic linear RGB to generic ST.2084 (PQ) encoded RGB mapping 1.0 to 100nits

We are actually decoding.

2024-08-12 07:47 UTC, KelSolaar commented
Ok, this is coming from the fact that we pull the description from the builtin transform but we do use it in the other direction...

2024-08-12 07:58 UTC, KelSolaar commented
Fixed!

2024-08-24 23:37 UTC, doug-walker commented
Hi Thomas! Items 3-9 in my above lists have been fixed! But of course, I've found some new items:

10. We should add "none" as an alias for Raw, since that's in the MaterialX list.
11. Please add CIE-XYZ-D65 as an alias for CIE-XYZ-D65 - Display-referred
12. The name "Gamma 2.2 Rec.709 - Texture" should be added as an alias.
13. "ACES2065-1" and "Linear AdobeRGB" are missing the "texture" category.
14. The OCIO 2.4 version of the CG config is no different than 2.3. I don't think we should release a config unless it has some useful difference from another one.

By the way, if you are blocked by not being able to merge this, please go ahead and we could catch any remaining items in a follow-up.

2024-08-25 21:27 UTC, doug-walker approved these changes
I reviewed the latest CG and Studio artifacts and they look good!

2024-08-25 21:28 UTC, KelSolaar commented
Took a few tries! Thanks for the review.

2024-08-25 21:28 UTC, merged